version: '3.8'
services:
  app:
    build: .
    container_name: ai-diary
    ports:
      - "5000:5000"
    volumes:
      - ./src/database:/app/src/database
    environment:
      SECRET_KEY: diary_app_secret_key_2025
    restart: unless-stopped
